spring.application.name=quizapp3
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://pg-2867f41a-aryansankar15-8396.i.aivencloud.com:25442/defaultdb  
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_YDHnT6MywlKrw7lSPQv
spring.jpa.hibernate.ddl-auto=update     
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


//the databse is not hosted on aiven change the details and connect to a new postgre sql table for using the application.
//it has been paused you can restart it.